services:
  tralala-frontend:
    image: nginx:latest
    container_name: tralala-frontend
    volumes:
      - ./public:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    restart: unless-stopped