services:
  tralala-serial-api:
    build: serial-api
    container_name: tralala-serial-api
    ports:
      - "5000:5000"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
